version: '3'
services:
  storage:
    image: dxflrs/garage:v2.3.0
    command: /garage server --single-node --default-bucket
    restart: unless-stopped
    expose:
      - 3900
      - 3901
      - 3903
    volumes:
      - garage:/data
      - ./conf/garage.toml:/etc/garage.toml:ro
    networks:
      - proxy
    environment:
      - GARAGE_DEFAULT_ACCESS_KEY=${GARAGE_ACCESS_KEY:?Please set the GARAGE_ACCESS_KEY environment variable or run setup tool}
      - GARAGE_DEFAULT_SECRET_KEY=${GARAGE_SECRET_KEY:?Please set the GARAGE_SECRET_KEY environment variable or run setup tool}
      - GARAGE_DEFAULT_BUCKET=namepending-bucket
    secrets:
      - source: garage-rpc-secret
        mode: 0600
      - source: garage-admin-token
        mode: 0600
  proxy:
    image: docker.io/caddy:alpine
    ports:
      - '${WEB_PORT:-8778}:80'
    volumes:
      - ./conf:/etc/caddy
    networks:
      - proxy
  db:
    image: docker.io/postgres:18
    restart: unless-stopped
    expose:
      - 5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASS:?Please set the POSTGRES_PASS environment variable or run setup tool}
      POSTGRES_USER: root
      POSTGRES_DB: namepending
    volumes:
      - pgdata:/var/lib/postgresql
      - postgres-socket:/var/run/postgresql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U root -d namepending']
      interval: 1s
      timeout: 5s
      retries: 10
  web:
    build:
      context: .
      target: web
    restart: unless-stopped
    networks:
      - default
      - proxy
    environment:
      - DATABASE_URL=postgres://root:${POSTGRES_PASS}@db:5432/namepending
      - APP_SECRET=${APP_SECRET:?Please set the APP_SECRET environment variable or run setup tool}
      - NODE_ENV=production
      - PROTOCOL_HEADER=x-forwarded-proto
      - HOST_HEADER=x-forwarded-host
      - URL=${URL:?Please set the URL environment variable or run setup tool}
      - PUBLIC_URL=${URL:?Please set the URL environment variable or run setup tool}
      - NAME=${NAME:-namepending}
      - DEMO=${DEMO:-false}
      - PUBLIC_NAME=${NAME:-namepending}
      - STEAM_API_KEY=${STEAM_API_KEY:?Please set the STEAM_API_KEY environment variable or run setup tool}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID:?Please set the DISCORD_CLIENT_ID environment variable or run setup tool}
      - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET:?Please set the DISCORD_CLIENT_SECRET environment variable or run setup tool}
      - SMTP_HOST=${SMTP_HOST:?Please set the SMTP_HOST environment variable or run setup tool}
      - SMTP_PORT=${SMTP_PORT:?Please set the SMTP_PORT environment variable or run setup tool}
      - SMTP_USER=${SMTP_USER:?Please set the SMTP_USER environment variable or run setup tool}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_FROM=${SMTP_FROM:?Please set the SMTP_FROM environment variable or run setup tool}
      - GARAGE_ACCESS_KEY=${GARAGE_ACCESS_KEY:?Please set the GARAGE_ACCESS_KEY environment variable or run setup tool}
      - GARAGE_SECRET_KEY=${GARAGE_SECRET_KEY:?Please set the GARAGE_SECRET_KEY environment variable or run setup tool}
      - GARAGE_URL=http://storage:3900
volumes:
  garage:
  pgdata:
  postgres-socket:
networks:
  proxy:
secrets:
  garage-rpc-secret:
    environment: GARAGE_PASS
  garage-admin-token:
    environment: GARAGE_PASS
