version: '3'
services:
  minio:
    image: docker.io/coollabsio/minio:RELEASE.2025-10-15T17-29-55Z
    command: server /data --console-address ":9001"
    restart: unless-stopped
    expose:
      - 9000
      - 9001
    volumes:
      - minio:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_PASS:?Please set the MINIO_PASS environment variable or run setup tool}
      MINIO_BROWSER_REDIRECT_URL: 'http://admin.s3.localhost'
    labels:
      - 'traefik.http.routers.minio.rule=Host(`s3.localhost`)'
      - 'traefik.http.routers.minio.service=minio-service'
      - 'traefik.http.services.minio-service.loadbalancer.server.port=9000'
      - 'traefik.http.routers.minio-admin.rule=Host(`admin.s3.localhost`)'
      - 'traefik.http.routers.minio-admin.service=minio-admin-service'
      - 'traefik.http.services.minio-admin-service.loadbalancer.server.port=9001'
  traefik:
    image: docker.io/traefik:v3.6
    command:
      - '--api.insecure=${TRAEFIK_DASHBOARD:-false}'
      - '--providers.docker=true'
      - '--entrypoints.web.address=:80'
      - '--entrypoints.web.forwardedHeaders.trustedIPs=10.88.0.0/8,127.0.0.1/32,172.18.0.1/32'
    ports:
      - '${TRAEFIK_WEB_PORT:-8778}:80'
      - '${TRAEFIK_DASHBOARD_PORT:-8781}:8080'
    volumes:
      - /var/run/user/1000/podman/podman.sock:/var/run/docker.sock
  db:
    image: docker.io/postgres:18
    restart: unless-stopped
    expose:
      - 5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASS:?Please set the POSTGRES_PASS environment variable or run setup tool}
    volumes:
      - pgdata:/var/lib/postgresql
      - postgres-socket:/var/run/postgresql
      - ./initrunner.sh:/docker-entrypoint-initdb.d/initrunner.sh:ro
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 1s
      timeout: 5s
      retries: 10
  migrate:
    depends_on:
      db:
        condition: service_healthy
    build:
      context: .
      target: migrate
    environment:
      - PGHOST=/var/run/postgresql
      - PGUSER=root
      - PGDATABASE=namepending
    volumes:
      - postgres-socket:/var/run/postgresql
    labels:
      - 'traefik.enable=false'
  api:
    depends_on:
      migrate:
        condition: service_completed_successfully
      db:
        condition: service_healthy
    build:
      context: .
      target: api
    restart: unless-stopped
    environment:
      - PGHOST=/var/run/postgresql
      - PGUSER=root
      - PGDATABASE=namepending
      - APP_SECRET=${APP_SECRET:?Please set the APP_SECRET environment variable or run setup tool}
      - BETTER_AUTH_SECRET=${APP_SECRET:?Please set the APP_SECRET environment variable or run setup tool}
      - BETTER_AUTH_URL=${URL:?Please set the URL environment variable or run setup tool}
      - URL=${URL:?Please set the URL environment variable or run setup tool}
    volumes:
      - postgres-socket:/var/run/postgresql
    labels:
      - 'traefik.http.routers.api.rule=PathPrefix(`/api`)'
  web:
    build:
      context: .
      target: web
    restart: unless-stopped
    environment:
      - PROTOCOL_HEADER=x-forwarded-proto
      - HOST_HEADER=x-forwarded-host
    labels:
      - 'traefik.http.routers.web.rule=PathPrefix(`/`)'
  whoami:
    image: traefik/whoami
    labels:
      - 'traefik.http.routers.whoami.rule=Host(`whoami.localhost`)'
volumes:
  minio:
  pgdata:
  postgres-socket:
